ytsaurus/ytsaurus-ui

packages/ui/src/ui/components/ACL/ACL-connect-helpers.js, packages/ui/src/ui/components/ACL/ACL.js, packages/ui/src/ui/components/ACL/ColumnGroups/ColumnGroups.tsx
https://nda.ya.ru/t/u1L3GqEV6qsUDY
=> fix: allow column groups create form only for `map_nodes` [YTFRONT-3901]

packages/ui/src/ui/pages/query-tracker/module/api.ts
According to issue #208, this PR addresses the difference between two queries: read_query_result and read_table.
=> Query results with more than 50 columns are not shown properly #208

packages/ui/src/ui/pages/query-tracker/QueryResultsView/ResultPaginator/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsView/index.scss, packages/ui/src/ui/pages/query-tracker/QueryResultsView/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts
Resolves #210
Added result row count and truncated flag info to results table
=> #210 - Add row count and "is_truncated" flag in query results

packages/ui/src/ui/components/ButtonPopup/ButtonPopup.scss, packages/ui/src/ui/components/ButtonPopup/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryFilesButton/QueryFilesButton.scss, packages/ui/src/ui/pages/query-tracker/QueryFilesButton/index.tsx, packages/ui/src/ui/pages/query-tracker/QuerySettingsButton/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryMetaForm/QueryEngineSelector/QueryEngineSelector.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryMetaForm/QueryMetaForm.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts
=> #211 - Add the ability to attach files to YQL queries in Query Tracker UI.

packages/ui/src/server/controllers/login.ts
I get an error during logout
```
[11:31:26 UTC] ERROR: [Express POST] [handleLogout] Error [61626bd4-50e3-4a00-9bac-883324230dec]
extra: {}
err: {
"type": "Object",
"message": "Cannot set headers after they are sent to the client",
"stack":
Error: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:405:5)
at ServerResponse.setHeader (node:_http_outgoing:648:11)
```
According to the documentation https://expressjs.com/ru/api.html#res.sendStatus the response status is sent along with the body
=> fix: nodejs error during logout

packages/ui/src/ui/containers/AppNavigation/AppNavigation.scss
This is a follow-up to fixing issue #225. It fixes the padding for pages that stretch across the whole screen.
=> fix(layout): the left menu disappears on long tables [#225]

packages/ui/src/ui/utils/scheduling/details.js
Do not evaluate aggregation for pools without resources, because it crushes application
=> fix: scheduling broken aggregation

packages/ui/src/ui/pages/components/tabs/Shards/NodeCount.tsx
I would like to start an long-term activity of migration javascript files to typescript.
In a sake of easy code review I will try:
1. Change only 1 module per PR.
2. Do not change the logic of module unless it is necessary for correct types.
=> refactor(NodeCount): migrate module to typescript

packages/ui/src/ui/containers/Host/Host.scss, packages/ui/src/ui/containers/Host/Host.tsx
Fix rendering long host in dynamic tables
**Before**
**After**
=> fix(Host): add ellipsis text in host

packages/ui/src/ui/pages/query-tracker/QueryResultsView/YQLTable/YQLTable.scss
I find out that truncated values shown incorrectly at queries page - not it's shown as empty cell.
The content of truncated cells should be shown [via that unipika css](https://github.com/gravity-ui/unipika/blob/af46643f184e955b87de5a992c1ebaa204e9dc8a/styles/unipika.scss#L121). 
In the same time, at YQLTable.scss I find the styles which override that behavior. It's not clear why we got these styles at the first place, I tried to remove them and it's fixed the issue.
Before patch: 
After patch:
PS: probably I should create an issue about the "cell size limit" for table cell? Right now the cells on queries page will always contain `[truncated]` value because we request data with default cell size limit.
=> fix(YQLTable): fix appearance of truncated value in cell

packages/ui/src/shared/constants/yt-api-id.ts, packages/ui/src/ui/components/Icon/importGravityIcons.ts, packages/ui/src/ui/constants/accounts/accounts.ts, packages/ui/src/ui/pages/components/SwitchLeaderShortInfo/SwitchLeaderShortInfo.scss, packages/ui/src/ui/pages/components/SwitchLeaderShortInfo/SwitchLeaderShortInfo.tsx, packages/ui/src/ui/pages/system/Masters/MasterGroup.js, packages/ui/src/ui/pages/system/Masters/SwitchLeader.tsx, packages/ui/src/ui/rum/rum-wrap-api.ts, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/reducers/system/masters.ts
https://nda.ya.ru/t/EnPm76mE75u5a4
In this PR I introduce a new button and dialog which switch leader for primary masters.
You can find this new button on the /system page, in masters section:
The feature was developed and tested only for primary masters because I don't have a cluster with secondary masters. 
PS: that my first meaningful PR in this project, so please give as much feedback as possible, I need to know how to develop things in right way.
=> feat(System): introduce new switch leader button

packages/ui/src/ui/pages/accounts/tabs/general/AccountsGeneralTab.js
By default user can see the warning that tablet resource accounting was moved to tablet cell bundles:
The problem is: user still sees it even if he manually switched enable_per_account_tablet_accounting flag in `//sys/@ui_config`.
=> fix(AccountsGeneralTab): do not show TabletAccountingNotice if enable_per_account_tablet_accounting is enabled

packages/ui/src/ui/UIFactory.tsx, packages/ui/src/ui/pages/navigation/Navigation/ContentViewer/helpers/getComponentByMode.ts, packages/ui/src/ui/pages/navigation/Navigation/Navigation.js, packages/ui/src/ui/store/actions/navigation/index.js, packages/ui/src/ui/store/selectors/navigation/navigation.ts
https://nda.ya.ru/t/atP5j4Lb76WCss
With this PR, custom yt installations can add their own tabs for navigation.
Here is an example - we added a new tab based on attributes:
``` typescript
const productionOverrides: Partial<UIFactory> = {
getNavigationExtention() {
const TAB_KEY = 'cutsom_tab_with_custom_tab';
return {
extendSupportedTabs({supportedTabs, attributes}) {
if (attributes.ui_flag_for_custom_ui) {
supportedTabs.add(TAB_KEY);
}
},
getDefaultMode(supportedTabs: Set<string>) {
if (supportedTabs.has(TAB_KEY)) {
return TAB_KEY;
}
return supportedTabs.has(NavigationTab.CONSUMER)
? NavigationTab.CONSUMER
: NavigationTab.CONTENT;
},
getSupportedAttributeTypes() {
function Stub() {
return <div>Here will be custom react component</div>;
}
return {
[TAB_KEY]: Stub,
};
}, …
```
=> feat: added ability to show custom tab in navigation view

packages/ui/src/shared/ui-settings.ts, packages/ui/src/ui/components/Login/LoginFormPage/LoginFormPage.tsx, packages/ui/src/ui/store/selectors/global/index.ts
https://github.com/ytsaurus/ytsaurus-ui/issues/636
Now we can change default text on login page via ui settings.
=> feat: added ability to override default text on login page

packages/ui/src/shared/ui-settings.ts, packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/components/Login/LoginFormPage/LoginFormPage.tsx, packages/ui/src/ui/store/selectors/global/index.ts
Hi there!
I made a mistake in https://github.com/ytsaurus/ytsaurus-ui/pull/645. The uiSettings did not allows to specify custom settings for different clusters, so the right place for such settings is cluster config, where we can specify settings per cluster.
=> fix: move loginPageSettings to cluster config, that is allows to specify such setting per cluster

packages/ui/src/ui/components/Modal/SimpleModal.tsx, packages/ui/src/ui/components/Yson/StructuredYsonVirtualized/StructuredYsonVirtualized.scss, packages/ui/src/ui/components/Yson/StructuredYsonVirtualized/StructuredYsonVirtualized.tsx, packages/ui/src/ui/components/Yson/Yson.tsx, packages/ui/src/ui/constants/navigation/modals/cell-preview.ts, packages/ui/src/ui/pages/navigation/Navigation/Navigation.js, packages/ui/src/ui/pages/navigation/content/Table/DataTableWrapper/DataTableWrapper.js, packages/ui/src/ui/pages/navigation/content/Table/DataTableWrapper/DataTableWrapper.scss, packages/ui/src/ui/pages/navigation/modals/CellPreviewModal/CellPreviewModal.scss, packages/ui/src/ui/pages/navigation/modals/CellPreviewModal/CellPreviewModal.tsx, packages/ui/src/ui/store/actions/navigation/modals/cell-preview.ts, packages/ui/src/ui/store/reducers/navigation/modals/cell-preview.ts, packages/ui/src/ui/store/reducers/navigation/modals/index.ts, packages/ui/src/ui/store/selectors/navigation/modals/cell-preview.ts, packages/ui/src/ui/store/selectors/thor/unipika.ts, packages/ui/src/ui/utils/navigation/content/table/table.js, packages/ui/src/ui/utils/navigation/prepareColumns.tsx
https://nda.ya.ru/t/V-VZJwcr77A6rS
Related to the [issue](https://github.com/ytsaurus/ytsaurus-ui/issues/655). 
I have added a view button to a cell when the value is truncated. When the user clicks on this button, it uses the yt command to read one specific cell from the current table and also has a 16MiB limit. 
The preview is displayed in a virtualized list that allows the json/yson format to be displayed.
=> feat(Table): add "view" button for truncated cells [#655]

packages/ui/src/ui/entries/main.tsx, packages/ui/src/ui/entries/yfm-overrides.scss
=> fix: added support for dark and light themes by override yfm styles [#712]

packages/ui/src/ui/pages/operations/OperationSuggestFilter/OperationSuggestFilter.js
Reproduce:
1. Open operation list page
2. Focus to 'pool', 'user' or 'poolTree' filter
3. Remove focus from filter by clicking to any element outside 
Visually filter will be looked like it's using default value instead of default value,
but in fact filter will be setted to empty string and you will get no results.
Fix:
Use default value if filter was updated with empty string.
=> fix(OperationsList): fix incorrect filters on OperationSuggestFilter blur [#705]

packages/ui/src/ui/pages/query-tracker/module/cell-preview/actions.ts
Error in interface
Error in debug mode
The root case - we don't have an array in `response.rows[0][options.columnName][0]`
=> fix(YQLTable): fixed exception in truncated cells preview

packages/ui/src/ui/pages/system/ProxiesImpl/StatsInfo.tsx
Appearance in master:
Appearance in this PR:
=> fix(System): fix color of stats text in dark mode

packages/ui/src/ui/pages/query-tracker/QueryResults/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/containers/ChartSettings/ChartSettings.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/preparers/d3config.ts
Adhoc charts were broken because of that commit https://github.com/ytsaurus/ytsaurus-ui/commit/b39aa3e873f44dd45da2c7bf8005ccb93294a40e and because of future chartkit update which is break chart if grid is disabled in x axis.
=> fix(Query): fix adhoc charts

packages/ui/src/server/utils/index.ts
It seems we found a bug in YT logs — axios errors are not logged correctly.
Why:
1. [Here is a sendAndLogError function which is used for logging.](https://github.com/ytsaurus/ytsaurus-ui/blob/f1c3ec3fc73a5bac17c0bffa2c3229a47c710ec3/packages/ui/src/server/utils/index.ts#L168C23-L168C38)
2. [And it has a separate branch for logging axios errors.](https://github.com/ytsaurus/ytsaurus-ui/blob/f1c3ec3fc73a5bac17c0bffa2c3229a47c710ec3/packages/ui/src/server/utils/index.ts#L177)
3. Logging looks like this: `ctx.logError('AxiosError', ae.toJSON(), extra);` what's important here is that the second argument is json.
4. [Second argument goes to extractErrorInfo function](https://github.com/gravity-ui/nodekit/blob/3c99b291bec166c8b3b13c92510db14c7e1b5321/src/lib/context.ts#L106).
5. [And in …
=> fix: fix logging of axios error in sendAndLogError function

packages/ui/src/ui/pages/odin/controls/OdinOverview.tsx
Open odin and check out date format in "Overview" and "Details" tab. 
Right now they are different, it's looks like a mistake.
=> fix(Odin): use the same format for DatePicker in odin

packages/ui/src/ui/containers/ClusterPage/ClusterPage.js, packages/ui/src/ui/containers/ClusterPage/ClusterPage.scss
Before this patch:
After this patch:
=> fix(ClusterPage): align "Loading <cluster name>..." text to center of the page

packages/ui/src/ui/containers/PathEditor/PathEditor.tsx, packages/ui/src/ui/pages/navigation/Navigation/NavigationTopRowContent.tsx, packages/ui/src/ui/pages/navigation/Navigation/PathEditorModal/DeleteObjectModal/DeleteObjectModal.js, packages/ui/src/ui/pages/navigation/Navigation/PathEditorModal/DeleteObjectModal/DeleteObjectModal.scss, packages/ui/src/ui/pages/navigation/Navigation/PathEditorModal/PathEditorModal.js
https://nda.ya.ru/t/eeesxrXE79bQKd
=> feat(Navigation): move "permanently delete" checkbox to footer of confirmation modal [YTFRONT-4245]

packages/ui/src/ui/components/ExpandIcon/ExpandIcon.tsx, packages/ui/src/ui/pages/groups/GroupsPageTable/GroupsPageTable.tsx, packages/ui/src/ui/store/actions/groups.ts, packages/ui/src/ui/store/selectors/groups.ts
Let's say we have 3 groups:
- vrozaev-test-group-1
- vrozaev-test-group-2
- vrozaev-test-group-3
And the hierarchy is: vrozaev-test-group-1 => vrozaev-test-group-2 => vrozaev-test-group-3
In this case we want to expand all parents of the node which is matches the filter.
1. Example: with "vrozaev-test-group-1" filter there will be no expanded nodes
1. Example: with "vrozaev-test-group-2" filter the "vrozaev-test-group-1" node will be expanded
1. Example: with "vrozaev-test-group-3" filter the "vrozaev-test-group-1" and "vrozaev-test-group-2" nodes will be expanded
=> fix(Groups): expand group tree on non-empty group filter [#853]

packages/ui/src/ui/containers/ACL/ACL.tsx, packages/ui/src/ui/utils/acl/index.ts
https://nda.ya.ru/t/QeZir5gH7ASZj6
=> chore(ACL): extract 'isGranted' method [YTFRONT-4560]

packages/ui/src/ui/components/ColumnCell/ColumnCell.tsx, packages/ui/src/ui/containers/CellPreviewModal/CellPreviewModal.tsx, packages/ui/src/ui/store/actions/navigation/modals/cell-preview/index.ts, packages/ui/src/ui/store/reducers/modals/cell-preview.ts
https://nda.ya.ru/t/vaxvrynx7Aif5u
=> fix(CellPreview): show preview button when yql v3 types disabled [#928]

packages/ui/src/ui/components/CommaSeparateListWithRestCounter/CommaSeparateListWithRestCounter.js
Issue: https://github.com/ytsaurus/ytsaurus-ui/issues/704.
Now we calculate text size in a correct way and user will see `+<number of hidden items>` if there is any.
=> fix(Users/Groups): fixed a bug when user could not see all group members or all groups of specific user [#704]

packages/ui/.eslintrc, packages/ui/src/ui/components/Dialog/Dialog.tsx, packages/ui/src/ui/components/DialogWrapper/DialogWrapper.tsx, packages/ui/src/ui/components/Modal/Modal.tsx, packages/ui/src/ui/components/Modal/SimpleModal.tsx, packages/ui/src/ui/components/ModalWrapper/ModalWrapper.tsx, packages/ui/src/ui/components/Yson/StructuredYsonVirtualized/StructuredYsonVirtualized.tsx, packages/ui/src/ui/containers/ACL/ManageAcl/ManageAcl.tsx, packages/ui/src/ui/containers/ACL/ManageInheritance/ManageInheritance.tsx, packages/ui/src/ui/containers/ManageTokens/ManageTokensModal.tsx, packages/ui/src/ui/containers/ManageTokens/ManageTokensPasswordModal/ManageTokensPasswordModal.tsx, packages/ui/src/ui/containers/ModalErrors/ModalErrors.tsx, packages/ui/src/ui/containers/RetryBatchModal/RetryBatchModal.tsx, packages/ui/src/ui/pages/chaos_cell_bundles/bundles/ChaosBundleEditorDialog/ChaosBundleEditorDialog.tsx, packages/ui/src/ui/pages/job/JobActions/JobActions.tsx, packages/ui/src/ui/pages/odin/controls/OdinOverview.tsx, packages/ui/src/ui/pages/scheduling/Content/tabs/Overview/Overview.js, packages/ui/src/ui/pages/scheduling/Scheduling/Scheduling.tsx, packages/ui/src/ui/pages/tablet/TabletDetails/Overview.js, packages/ui/src/ui/pages/tablet/TabletDetails/StoresDialog.tsx
Issue: https://github.com/ytsaurus/ytsaurus-ui/issues/768
The rootcase of the issue is a way of hotkeys declaration via hotkeys-js.
Each hotkey is declared in some scope. Now that scope stays the same when any modal windows opens. That means that hotkeys from the page could be triggered with opened modal window, which might lead to unforeseen results.
The obvious solution here is switching hotkeys scope once any modal window become visible. That prevent page hotkeys from firing. 
So we need to modify all code which shows any king of modal windows and add there a scope switch.
1. packages/ui/src/ui/components/Dialog/Dialog.tsx
2. packages/ui/src/ui/components/Modal/Modal.tsx
3. packages/ui/src/ui/components/Modal/SimpleModal.tsx
Also, there are a lot of direct usage of `Dialog` and `Modal` …
=> fix: prevent page hotkeys firing with opened YTDialog [#768]

packages/ui/src/ui/components/common/Datepicker/PopupContent/PopupContent.scss
=> fix: added proper padding in datepicker popup

packages/ui/src/ui/pages/query-tracker/QueryACO/EditQueryACOModal/EditQueryACOModal.tsx
Issue: https://github.com/ytsaurus/ytsaurus-ui/issues/1126
=> fix: allow empty ACO for existing query

packages/ui/src/ui/pages/query-tracker/module/query/actions.ts
https://github.com/ytsaurus/ytsaurus-ui/issues/1150
=> fix: always setted non-empty engine value in query-tracker [#1150]
