packages/ui/src/ui/components/ACL/ACL.js, packages/ui/src/ui/components/ACL/ACL.scss, packages/ui/src/ui/components/ACL/ColumnGroups/ColumnGroups.scss, packages/ui/src/ui/components/ACL/ColumnGroups/ColumnGroups.tsx, packages/ui/src/ui/components/ACL/UserPermissions/UserPermissions.scss
- reworked all ACL tables with DataTableYT component
- adjusted column width settings (tried to avoid overlapping and get almost same width for similar columns on this page)
=> fix: ACL page tables styles [YTFRONT-3758]

packages/ui/src/ui/constants/components/nodes/nodes.ts, packages/ui/src/ui/pages/components/tabs/nodes/Nodes/Nodes.scss, packages/ui/src/ui/store/reducers/components/nodes/nodes/node.tsx, packages/ui/src/ui/utils/components/nodes/tables.tsx
https://nda.ya.ru/t/HJzzfCiT6TsAgp
=> feat(Components/Nodes): Add 'Chaos slots' view mode [YTFRONT-3333]

packages/ui/src/ui/pages/query-tracker/QueryResultsView/ResultsTable.tsx, packages/ui/src/ui/pages/query-tracker/module/query_result/utils/format.ts
Arcanum link: https://nda.ya.ru/t/x-CECAO46VmeKP
Query to test: https://nda.ya.ru/t/dU3bnvVn6VsBSY
=> fix: QT format decimal number results [YTFRONT-3782]

packages/ui/src/ui/store/actions/components/nodes/nodes.ts, packages/ui/src/ui/store/reducers/components/nodes/nodes/node.tsx, packages/ui/src/ui/store/reducers/components/nodes/nodes/nodes.ts, packages/ui/src/ui/utils/components/nodes/tables.tsx
https://nda.ya.ru/t/WFzNczfp6UhMf9
=> Components/Nodes: use attributes.paths

packages/ui/src/shared/yt-types.ts, packages/ui/src/ui/pages/query-tracker/QueriesList/EditQueryNameModal/EditQueryNameModal.tsx, packages/ui/src/ui/pages/query-tracker/QueriesList/QueriesHistoryList/index.scss, packages/ui/src/ui/pages/query-tracker/QueriesList/QueriesHistoryList/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryTracker/QueryTracker.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts, packages/ui/src/ui/rum/rum-wrap-api.ts
https://nda.ya.ru/t/-Uj59-vG6Visww
=> feat: enable query name editing [YTFRONT-3649]

packages/ui/src/ui/common/thor/utils.spec.js, packages/ui/src/ui/common/thor/utils.ts, packages/ui/src/ui/common/thor/ypath.js, packages/ui/src/ui/common/thor/ypath.spec.js, packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/AlertEvents/AlertEvents.tsx, packages/ui/src/ui/pages/scheduling/Content/PoolMetaData.tsx, packages/ui/src/ui/pages/scheduling/Scheduling/PoolEditorDialog/PoolEditorDialog.tsx, packages/ui/src/ui/store/actions/operations/detail.js, packages/ui/src/ui/store/selectors/job/detail.ts, packages/ui/src/ui/store/selectors/navigation/content/replicated-table.ts, packages/ui/src/ui/store/selectors/operations/operation.ts, packages/ui/src/ui/store/selectors/scheduling/scheduling-ts.tsx, packages/ui/src/ui/utils/navigation/tabs/tables.js, packages/ui/src/ui/utils/scheduling/scheduling.ts, packages/ui/tests/init-cluster-e2e.sh
https://nda.ya.ru/t/n-Iq4RjF6W2tVW
=> fix: PoolEditorDialog weight field remove request when value was not changed [YTFRONT-3748]

packages/ui/src/shared/constants/settings.ts, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/pages/query-tracker/QueriesList/EditQueryNameModal/EditQueryNameModal.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryResultDownloadManager.tsx, packages/ui/src/ui/pages/query-tracker/QueryWidget/index.tsx, packages/ui/src/ui/pages/query-tracker/hooks/QueriesPooling/QueriesPolling.tsx, packages/ui/src/ui/pages/query-tracker/hooks/QueriesPooling/context.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/queries_list/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/query_result/actions.ts, packages/ui/src/ui/store/selectors/settings-ts.ts, packages/ui/src/ui/store/thunkDispatch.ts
https://nda.ya.ru/t/ERLAgHms6Wifso
=> feat(QT): add QT settings override with UI [YTFRONT-3790]

packages/ui/src/shared/yt-types.ts, packages/ui/src/ui/components/DataTableYT/DataTableYT.tsx, packages/ui/src/ui/components/Yson/StructuredYsonVirtualized/StructuredYsonVirtualized.tsx, packages/ui/src/ui/pages/components/tabs/node/NodeMemoryDetailsTable/NodeMemoryDetailsTable.tsx, packages/ui/src/ui/store/actions/components/node/node.ts, packages/ui/src/ui/store/actions/components/nodes/nodes.ts, packages/ui/src/ui/utils/cypress-attributes.ts
https://nda.ya.ru/t/aSRdr3IE6WzmwK
=> fix(Components/Node): bring back 'Locations' tab [YTFRONT-3796]

packages/ui/src/ui/store/actions/job/specification.ts
https://nda.ya.ru/t/we4P51LJ6ZRbgQ
=> feat(Job/Specification): read from 'job_spec_ext' [YTFRONT-3802]

packages/ui/src/ui/pages/query-tracker/QueriesList/QueriesHistoryList/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/hooks/useCurrentQuery.ts, packages/ui/src/ui/pages/query-tracker/hooks/QueriesPooling/QueriesPolling.tsx, packages/ui/src/ui/pages/query-tracker/hooks/QueriesPooling/context.tsx
https://nda.ya.ru/t/aecYNUuG6eP3V6
=> fix(QT): refactor polling, fix endless running state [YTFRONT-3852]

packages/ui/src/ui/utils/index.ts, packages/ui/src/ui/utils/navigation/content/map-nodes/node.js, packages/ui/tests/e2e/pages/navigation.base.spec.ts, packages/ui/tests/init-cluster-e2e.sh
https://nda.ya.ru/t/Yd5eWtNg6ezXLd
=> fix: display cyrillic nodes caption and breadcrumbs [YTFRONT-3784]

packages/ui/src/ui/pages/tablet/TabletDetails/Overview.js
https://nda.ya.ru/t/HB6Yw9Ij6e3HYC
=> feat(Tablet): turn off StoresDialog for tablet with more than 200 stores [YTFRONT-3766]

packages/ui/src/shared/yt-types.ts, packages/ui/src/ui/components/BundleMetaResourceProgress/BundleMetaResourceProgress.tsx, packages/ui/src/ui/components/ColorCircle/ColorCircle.scss, packages/ui/src/ui/components/ColorCircle/ColorCircle.tsx, packages/ui/src/ui/components/MetaTable/MetaTable.tsx, packages/ui/src/ui/constants/index.ts, packages/ui/src/ui/pages/chaos_cell_bundles/bundles/BundlesTable.connected.ts, packages/ui/src/ui/pages/tablet_cell_bundles/TabletCellBundles.tsx, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.scss, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.tsx, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundlesTable.connected.ts, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundlesTable.tsx, packages/ui/src/ui/rum/rum-wrap-api.ts, packages/ui/src/ui/store/actions/tablet_cell_bundles/index.ts, packages/ui/src/ui/store/reducers/tablet_cell_bundles/index.ts, packages/ui/src/ui/store/reducers/tablet_cell_bundles/tablet-cell-bundle-editor.ts, packages/ui/src/ui/store/selectors/tablet_cell_bundles/index.ts, packages/ui/src/ui/utils/acl/acl-api.ts, packages/ui/src/ui/utils/acl/index.ts, packages/ui/src/ui/utils/tablet_cell_bundles/bundles/bundle-editor-dialog/index.ts
https://nda.ya.ru/t/OqD3q0Qk6ZBQGB
=> fixes for BundleEditor

packages/ui/src/ui/pages/system/Masters/MasterGroup.js, packages/ui/src/ui/pages/system/Masters/MasterGroup.scss, packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/src/ui/pages/system/NodeQuad/NodeQuad.scss
https://nda.ya.ru/t/ORDhQDPu6h4oe6
=> fix(System/Masters): minor fixes for 'voting' flag [YTFRONT-3832]

.github/workflows/ci-e2e.yaml, packages/ui/scripts/dev.localmode-env.sh, packages/ui/src/server/components/cluster-params.ts, packages/ui/src/server/configs/e2e/local.ts, packages/ui/src/shared/constants/index.ts, packages/ui/src/ui/components/MetaTable/presets/ttl.tsx, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/store/actions/cluster-params.ts, packages/ui/src/ui/store/actions/navigation/content/map-node.js, packages/ui/src/ui/store/actions/navigation/index.js, packages/ui/src/ui/store/actions/navigation/modals/attributes-editor.tsx, packages/ui/src/ui/store/actions/system/chunks.js, packages/ui/src/ui/store/actions/system/masters.js, packages/ui/src/ui/store/actions/system/resources.js, packages/ui/src/ui/store/actions/system/rpc-proxies.ts, packages/ui/src/ui/store/actions/system/schedulers.js, packages/ui/src/ui/store/reducers/global/index.js, packages/ui/src/ui/store/reducers/index.ts, packages/ui/src/ui/store/reducers/tables.js, packages/ui/src/ui/store/selectors/global/index.ts, packages/ui/src/ui/store/selectors/navigation/content/map-node.js, packages/ui/src/ui/store/selectors/thor/support.js, packages/ui/tests/e2e/pages/scheduling.base.spec.ts
https://nda.ya.ru/t/TiVTJdu46iKCGe
=> Use /@effective_expiration attribute [YTFRONT-3665]

packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/utils/query.ts
https://nda.ya.ru/t/GrgfRC4j6kDucF
=> feat(QT): add SPYT engine option [YTFRONT-3872]

.github/workflows/ci-e2e.yaml, packages/ui/scripts/dev.localmode-env.sh, packages/ui/src/ui/entries/main.tsx, packages/ui/src/ui/store/actions/scheduling/scheduling-operations.tsx, packages/ui/src/ui/store/selectors/scheduling/scheduling-pools.ts, packages/ui/tests/e2e/pages/scheduling.base.spec.ts, packages/ui/tests/init-cluster-e2e.sh
https://nda.ya.ru/t/Ubignpg_6kUu76
=> fix(Scheduling): Ephemeral pools should be visible [YTFRONT-3708]

packages/ui/babel.config.js, packages/ui/package.json
https://nda.ya.ru/t/hXVMsfdv6w8TPR
=> fix: babel config app-builder conflict

packages/ui/deploy/nginx/yt.development.conf.example
Removed erroneous include from nginx config template
=> chore (deploy): remove yql include

packages/ui/src/ui/pages/query-tracker/QuerySettingsButton/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/WKFiK-q66xv8mW
=> fix(QT): yql stage setting should not affect other engines requests

packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/utils/query_generate.ts
I added default query and cluster setting for the SPYT engine.
=> Add defaults for QT SPYT queries

packages/ui/README.md
This fix actually made to fore new version release
=> fix: readme Development section improve

packages/ui/src/ui/UIFactory.tsx, packages/ui/src/ui/constants/navigation/tabs/schema.js, packages/ui/src/ui/pages/navigation/tabs/Schema/ExternalDescription/ExternalDescription.tsx, packages/ui/src/ui/pages/navigation/tabs/Schema/Schema.tsx, packages/ui/src/ui/store/actions/navigation/tabs/schema.js, packages/ui/src/ui/store/reducers/navigation/tabs/schema/schema.js
https://nda.ya.ru/t/T84ED21o72uiXA
=> Add external title column [YTFRONT-3939]

packages/ui/src/@types/types.d.ts, packages/ui/src/ui/components/Dialog/controls/PoolTreeSuggestControl/PoolTreeSuggestControl.tsx, packages/ui/src/ui/components/templates/system.js, packages/ui/src/ui/pages/navigation/modals/RemoteCopyModal.tsx, packages/ui/src/ui/pages/scheduling/Scheduling/SchedulingTopRowContent.tsx, packages/ui/src/ui/store/selectors/components/nodes/nodes/predicates.ts
https://a.yandex-team.ru/review/5003777/details
=> minor fixes

packages/ui/src/ui/components/Loader/Loader.scss, packages/ui/src/ui/components/Loader/Loader.tsx, packages/ui/src/ui/components/MonacoEditor/MonacoEditor.tsx, packages/ui/src/ui/components/MonacoEditor/index.tsx, packages/ui/src/ui/containers/AppNavigation/TopRowContent/TopRowContent.tsx, packages/ui/src/ui/hocs/withLazyLoading.tsx, packages/ui/src/ui/pages/navigation/AnnotationEditor/AnnotationEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryTracker/index.scss, packages/ui/src/ui/pages/query-tracker/QueryTracker/index.tsx
https://nda.ya.ru/t/s597uxfA73vvT5
=> separate chunk for MonacoEditor

packages/ui/src/ui/pages/components/tabs/node/NodeLocations/NodeLocations.tsx, packages/ui/src/ui/pages/components/tabs/nodes/NodeCard/NodeCard.js
https://github.com/ytsaurus/ytsaurus-ui/issues/204
=> feat: display location ids on data node table [#204]

packages/ui/src/ui/hooks/use-prevent-unload.ts, packages/ui/src/ui/pages/query-tracker/QueryTracker/QueryTracker.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts
=> feat: Prevent user from closing the tab/browser window with unsaved query text #226

packages/ui/src/ui/components/OperationPool/OperationPool.tsx, packages/ui/src/ui/components/UserLink/UserLink.scss, packages/ui/src/ui/pages/chyt/ChytPageClique/ChytPageCliqueSpeclet.scss, packages/ui/src/ui/pages/chyt/ChytPageClique/ChytPageCliqueSpeclet.tsx, packages/ui/src/ui/pages/chyt/ChytPageList/ChytPageListTable.scss, packages/ui/src/ui/pages/chyt/ChytPageList/ChytPageListTable.tsx, packages/ui/src/ui/pages/chyt/components/CliqueState.tsx, packages/ui/src/ui/store/actions/chyt/options.ts, packages/ui/src/ui/store/actions/chyt/speclet.ts, packages/ui/src/ui/store/reducers/chyt/clique.ts, packages/ui/src/ui/store/reducers/chyt/options.ts, packages/ui/src/ui/store/reducers/chyt/speclet.ts
https://nda.ya.ru/t/B__HtSZG74GUHg
=> fix(CHYT): minor fixes [YTFRONT-3863]

packages/ui/src/ui/components/WithStickyToolbar/Toolbar/Toolbar.scss, packages/ui/src/ui/components/WithStickyToolbar/Toolbar/Toolbar.tsx, packages/ui/src/ui/pages/query-tracker/NewQueryButton/NewQueryButton.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QuerySettingsButton/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryMetaForm/QueryMetaForm.scss, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryMetaForm/QueryMetaForm.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryWidget/index.scss, packages/ui/src/ui/pages/query-tracker/QueryWidget/index.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/tests/.gitignore, packages/ui/tests/e2e/pages/query-tracker.spec.ts, packages/ui/tests/e2e/utils/BasePage.ts, packages/ui/tests/playwright.config.ts
https://github.com/ytsaurus/ytsaurus-ui/issues/238
=> feat: added a new query button #238

packages/ui/src/ui/constants/components/nodes/node.ts, packages/ui/src/ui/pages/components/tabs/node/NodePage.tsx, packages/ui/src/ui/pages/components/tabs/node/NodeUnrecognizedOptions/NodeUnrecognizedOptions.scss, packages/ui/src/ui/pages/components/tabs/node/NodeUnrecognizedOptions/NodeUnrecognizedOptions.tsx, packages/ui/src/ui/rum/rum-wrap-api.ts, packages/ui/src/ui/store/actions/components/node/node.ts, packages/ui/src/ui/store/actions/components/node/unrecognized-options.ts, packages/ui/src/ui/store/reducers/components/node/index.ts, packages/ui/src/ui/store/reducers/components/node/node.ts, packages/ui/src/ui/store/reducers/components/node/unrecognized-options.ts, packages/ui/src/ui/store/selectors/components/node/unrecognized-options.ts, packages/ui/src/ui/store/selectors/thor/unipika.ts
https://nda.ya.ru/t/4FYfPimL74MmUj
=> feat(Components/Node): add 'Unrecognized options' tab [YTFRONT-3936]

packages/ui/src/ui/pages/query-tracker/QueryResultsView/YQLTable/YQLTable.tsx
https://github.com/ytsaurus/ytsaurus-ui/issues/294
=> fix: synchronize table header when resizing [#294]

packages/ui/src/ui/constants/docsUrls.ts, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.tsx, packages/ui/src/ui/store/actions/tablet_cell_bundles/index.ts, packages/ui/src/ui/store/reducers/tablet_cell_bundles/index.ts, packages/ui/src/ui/utils/tablet_cell_bundles/bundles/bundle-editor-dialog/index.ts
https://nda.ya.ru/t/FlGlj43Q74MbU6
=> fix: add bundle resources validation

packages/ui/docs/configuration.md, packages/ui/src/@types/core.d.ts, packages/ui/src/server/components/layout-config.ts, packages/ui/src/server/components/oauth.ts, packages/ui/src/server/components/yt-auth.ts, packages/ui/src/server/controllers/login.ts, packages/ui/src/server/controllers/logout.ts, packages/ui/src/server/controllers/oauth-login.ts, packages/ui/src/server/index.ts, packages/ui/src/server/middlewares/authorization.ts, packages/ui/src/server/middlewares/oauth.ts, packages/ui/src/server/middlewares/yt-auth.ts, packages/ui/src/server/routes.ts, packages/ui/src/server/utils/authorization.ts, packages/ui/src/shared/constants/index.ts, packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/components/Login/LoginFormPage/LoginFormPage.tsx, packages/ui/src/ui/components/Login/LoginPageWrapper/LoginPageWrapper.scss, packages/ui/src/ui/containers/AppNavigation/AppNavigation.tsx, packages/ui/src/ui/containers/AppNavigation/AppNavigationComponent.tsx, packages/ui/src/ui/containers/AppNavigation/AppNavigationPageLayout.tsx, packages/ui/src/ui/store/reducers/global/index.js, packages/ui/src/ui/store/selectors/global/index.ts
https://nda.ya.ru/t/R668FkL_74KJ3V
=> feat: implement an OAuth authorize

packages/ui/src/ui/rum/constants.ts, packages/ui/src/ui/rum/rum-counter.ts, packages/ui/src/ui/store/actions/system/masters.js, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/reducers/system/masters.ts, packages/ui/src/ui/store/selectors/system/masters.ts, packages/ui/tests/e2e/pages/navigation.base.spec.ts
https://nda.ya.ru/t/VL2P5eED74U34k
=> fix: update the cell tag 

packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/src/ui/pages/system/Masters/Masters.scss, packages/ui/src/ui/pages/system/Masters/SystemAlert.tsx, packages/ui/src/ui/pages/system/SystemStateOverview/SystemStateLabels.tsx, packages/ui/src/ui/pages/system/SystemStateOverview/SystemStateOverview.tsx, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/reducers/system/masters.ts, packages/ui/src/ui/store/selectors/system/index.js, packages/ui/src/ui/store/selectors/system/index.ts, packages/ui/src/ui/store/selectors/system/masters.ts
https://nda.ya.ru/t/e2uy0kMi74hiRo
=> feat(System): add //sys/@master_alerts [YTFRONT-3960]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/scripts/sync-peer-dependencies.js, packages/ui/src/@types/types.d.ts, packages/ui/src/ui/components/QuotaEditor/QuotaEditor.tsx, packages/ui/src/ui/hocs/components/Modal/withScope.tsx, packages/ui/src/ui/hooks/use-hotkeysjs-scope.ts, packages/ui/src/ui/pages/tablet_cell_bundles/bundle/BundleConfigurationMeta.scss, packages/ui/src/ui/pages/tablet_cell_bundles/bundle/BundleConfigurationMeta.tsx, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.scss, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.tsx, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/selectors/scheduling/scheduling-pools.ts, packages/ui/src/ui/utils/scheduling/detailsTable.tsx, packages/ui/src/ui/utils/tablet_cell_bundles/bundles/bundle-editor-dialog/index.ts, packages/ui/src/ui/utils/utils.tsx
https://nda.ya.ru/t/sZGW154874peQT
=> some fixes

packages/ui/src/ui/components/CollapsedString/CollapsedString.scss, packages/ui/src/ui/components/CollapsedString/CollapsedString.tsx, packages/ui/src/ui/components/CollapsedString/index.ts, packages/ui/src/ui/components/ExpandButton/ExpandButton.scss, packages/ui/src/ui/components/ExpandButton/ExpandButton.tsx, packages/ui/src/ui/components/ExpandButton/index.ts, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorCloud.scss, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorCloud.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorList.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTree.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.scss, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/index.ts, packages/ui/src/ui/pages/query-tracker/QueryResults/helpers/calculateCloudLevel.ts, packages/ui/src/ui/pages/query-tracker/QueryResults/helpers/getIssuePosition.ts, packages/ui/src/ui/pages/query-tracker/QueryResults/helpers/index.ts, packages/ui/src/ui/pages/query-tracker/QueryResults/index.tsx, packages/ui/src/ui/pages/query-tracker/context/MonacoContext.ts, packages/ui/src/ui/pages/query-tracker/hooks/useMonaco.ts, packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/j3KdT3hE74yJ9o
=> feat(Query): new query error component [YTFRONT-4000]

packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts
https://nda.ya.ru/t/FAQGhP_j755CFE
=> fix(Query): underline in monaco [YTFRONT-4069]

packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryProgress.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/JRL8mEdl74yJ8a
=> feat(Query): progress for spyt engine [YTFRONT-3981]

packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.scss, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.tsx
https://nda.ya.ru/t/yoGCHLk075Bqhk
=> fix(Query): fixed error text selection [YTFRONT-4089]

packages/ui/src/ui/pages/navigation/tabs/Schema/Schema.scss
https://nda.ya.ru/t/tp249O8775G7kD
=> fix(Navigation): wrong schema col width [YTFRONT-4092]

packages/ui/src/ui/utils/navigation/navigation.ts
https://nda.ya.ru/t/clQ_9gZu75Fo3j
=> fix(Navigation): wrong path to table in notification [YTFRONT-4091]

packages/ui/src/ui/pages/query-tracker/Plan/NodeStages.tsx
https://nda.ya.ru/t/kFG1MwmH75H4tc
=> fix(Query): fix progress stages view [YTFRONT-4097]

packages/ui/src/shared/keys-by-dot.ts, packages/ui/src/ui/utils/tablet_cell_bundles/bundles/bundle-editor-dialog/index.ts
https://nda.ya.ru/t/QU2Ddt7C75GyHP
=> fix(Bundles/Editor): Memory/Reserved should be editable [YTFRONT-4098]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/ui/hooks/useAppSelector.ts, packages/ui/src/ui/store/index.ts, packages/ui/src/ui/store/window-store.ts
https://nda.ya.ru/t/Y244myUs75F7Ns
=> feat: add redux toolkit [YTFRONT-4094]

packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts
https://nda.ya.ru/t/qkaNlvz975HzT8
=> fix(Query): clique disabled by history query [YTFRONT-4105]

packages/ui/src/ui/utils/url-mapping.ts
https://nda.ya.ru/t/WYvyvoCE75J3qJ
=> fix(Navigation): emojis in names [YTFRONT-4104]

packages/ui/src/ui/store/index.ts
https://a.yandex-team.ru/review/5728959/details
=> fix(Store): change redux toolkit configuration [YTFRONT-4115]

packages/ui/src/ui/pages/navigation/content/Table/DataTableWrapper/DataTableWrapper.js
https://a.yandex-team.ru/review/5725329/details
=> fix(Navigation/Table): sync width of headers with data [YTFRONT-4109]

packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/YB9Fk6WO75NcbE
=> fix(Query): error while parsing yson [YTFRONT-4110]

packages/ui/src/ui/pages/query-tracker/NewQueryButton/NewQueryButton.tsx, packages/ui/src/ui/pages/query-tracker/utils/navigation.ts
https://nda.ya.ru/t/dZK_dxna75TtPU
=> feat(Query): change new query button to link [YTFRONT-4093]

packages/ui/src/ui/pages/components/TableInfo/TableInfo.tsx
Another module was migrated to typescript, there are no changes in logic, only types.
=> refactor(TableInfo): migrate module to typescript

packages/ui/package.json
Introduced npm script for type checking - `npm run typecheck`.
It could be useful during development and in PR checks.
=> chore(npm scripts): added npm script for typecheck - "npm run typecheck"

packages/ui/src/ui/pages/components/tabs/Shards/Name.tsx
Another module was migrated to typescript, there are no changes in logic, only types.
=> refactor(Name): migrate module to typescript

packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.keywords.ts, packages/ui/src/ui/libs/monaco-yql-languages/loadWebsqlAutocomplete.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.keywords.ts
https://nda.ya.ru/t/9w_I9YJi75Vm8X
=> fix(Query): autocompete error old safari [YTFRONT-4125]

packages/ui/src/ui/pages/navigation/tabs/Schema/Schema.tsx
https://nda.ya.ru/t/Vu7AITDw75btW2
=> fix(Navigation): wrong symlinks path [YTFRONT-4128]

packages/ui/src/ui/pages/navigation/tabs/Tablets/Tablets.js, packages/ui/src/ui/pages/navigation/tabs/Tablets/Tablets.scss
https://nda.ya.ru/t/9Lga7Bpf75byEH
=> fix(Navigation): text bug in tablets layout [YTFRONT-4133]

packages/ui/src/ui/pages/accounts/tabs/detailed-usage/AccountUsageToolbar.tsx
https://nda.ya.ru/t/_NxufOYd75j7kM
=> fix(Accounts): select problem [YTADMINREQ-41653]

packages/ui/src/ui/components/ColumnSelector/ColumnSelector.js
https://nda.ya.ru/t/r1rrmQW075bx4y
=> feat(Navigation): sort button in table columns [YTFRONT-4135]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/ui/pages/odin/_actions/odin-overview.ts, packages/ui/src/ui/pages/odin/_reducers/odin-overview.ts, packages/ui/src/ui/pages/odin/_reducers/url-mapping.ts, packages/ui/src/ui/pages/odin/_selectors/odin-overview.ts, packages/ui/src/ui/pages/odin/controls/OdinOverview.scss, packages/ui/src/ui/pages/odin/controls/OdinOverview.tsx, packages/ui/src/ui/pages/odin/index.ts, packages/ui/src/ui/pages/odin/odin-utils.ts
https://nda.ya.ru/t/F57IC79475siLM
=> feat(Odin): added timepicker on overview [YTFRONT-2733]

packages/ui/src/ui/store/selectors/chaos_cell_bundles/index.ts, packages/ui/src/ui/store/selectors/tablet_cell_bundles/index.ts, packages/ui/src/ui/utils/tablet_cell_bundles/index.ts
https://nda.ya.ru/t/Ulr7IC8175uQSi
https://nda.ya.ru/t/3nD2AQDc75sc26
=> fix(Bundles): sort by node [YTFRONT-4131]

packages/ui/src/ui/store/actions/tablet_cell_bundles/tablet-cell-bundle-editor.ts
https://nda.ya.ru/t/zD4JHOT675uY9o
null
=> fix(Bundles): memory limit [YTFRONT-4170]

packages/ui/src/ui/components/AclUpdateMessage/AclUpdateMessage.scss, packages/ui/src/ui/components/AclUpdateMessage/AclUpdateMessage.tsx, packages/ui/src/ui/components/common/Timeline/TimelinePicker/TimelinePicker.scss, packages/ui/src/ui/containers/ACL/ACL.tsx, packages/ui/src/ui/navigation/Navigation/PathEditorModal/CreateTableModal/CreateTableModal.tsx, packages/ui/src/ui/pages/navigation/content/Table/DownloadManager/DownloadManager.tsx, packages/ui/src/ui/pages/navigation/tabs/Schema/Schema.scss, packages/ui/src/ui/pages/navigation/tabs/Schema/Schema.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryResultDownloadManager.tsx, packages/ui/src/ui/pages/scheduling/Content/tabs/Overview/Overview.js, packages/ui/src/ui/pages/scheduling/Content/tabs/PoolAcl/PoolAcl.js, packages/ui/src/ui/pages/system/Chunks/Chunks.js, packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/src/ui/pages/system/Masters/Masters.scss, packages/ui/src/ui/store/actions/operations/detail.ts, packages/ui/src/ui/store/actions/operations/utils.js, packages/ui/src/ui/store/actions/scheduling/expanded-pools.tsx, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/reducers/navigation/content/table/table.js, packages/ui/src/ui/store/reducers/operations/jobs/jobs.js, packages/ui/src/ui/store/reducers/operations/jobs/url-mapping.ts, packages/ui/src/ui/store/selectors/navigation/content/table.js, packages/ui/src/ui/store/selectors/operations/index.ts, packages/ui/src/ui/utils/utils.tsx
https://nda.ya.ru/t/LRGFJGCZ767kyb
=> some minor improvements

packages/ui/build.lib.config.ts, packages/ui/build.server.tsconfig.json, packages/ui/package.json
@vrozaev, please check if it solves your issue with `@ytsaurus/ui` package
=> chore: bring back 'npm run build:lib'

packages/ui/src/ui/UIFactory.tsx, packages/ui/src/ui/containers/ClusterPage/ClusterPage.js, packages/ui/src/ui/containers/ClusterPage/ClusterPage.scss, packages/ui/src/ui/containers/ClustersMenu/ClustersMenu.js, packages/ui/src/ui/containers/RootPage/RootPage.scss, packages/ui/src/ui/containers/RootPage/RootPage.tsx
https://nda.ya.ru/t/bBDv_85P7633Hx
https://nda.ya.ru/t/-W5OB7ff7633Kp
=> feat: add footer factory method [YTFRONT-4173]

packages/ui/src/ui/components/Pagination/Pagination.js, packages/ui/src/ui/pages/navigation/content/Table/DownloadManager/DownloadManager.tsx
https://nda.ya.ru/t/cusDhQGZ76ESVS
=> fix(DownloadManager): fix for ranges [YTFRONT-4215]]

packages/ui/src/ui/pages/query-tracker/QueryResults/hooks/useQueryResultTabs.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts
https://nda.ya.ru/t/Ktcz1dbX7645Eb
https://nda.ya.ru/t/369LYQ7Z76458u
=> fix(Query): query and progress tab [YTFRONT-4185]

packages/ui/src/ui/pages/components/tabs/node/NodeGeneralTab/NodeGeneralTab.tsx
https://nda.ya.ru/t/4q8o2EFs763BEe
=> feat(Components): alert for offline node [YTFRONT-4153]

packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.scss
https://nda.ya.ru/t/8WBS2Jja76AYtD
=> fix(Query): select in error line [YTFRONT-4208]

packages/ui/src/ui/pages/system/Masters/MasterGroup.scss
https://nda.ya.ru/t/DEn61JgQ76AaYK
=> fix(System): nonvoting position [YTFRONT-4209]

packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryTracker/QueryEditorSplit.tsx, packages/ui/src/ui/store/actions/global/index.ts
https://nda.ya.ru/t/uX72lVGY76AfjZ
=> feat(Query): title with query data [YTFRONT-4186]

packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/8PLJRXyu76AqvQ
=> fix(Query): utf decode in result table [#533]

packages/ui/src/ui/containers/ClusterPage/ClusterPage.js
https://a.yandex-team.ru/review/6038384/files/1
=> fix(Navigation): widget with footer problem [YTFRONT-4221]

packages/ui/src/ui/containers/ClusterPage/ClusterPage.js, packages/ui/src/ui/containers/ClustersMenu/ClusterMenuBody.scss
https://nda.ya.ru/t/e0dVcqq676PuAv
=> fix(Cluster menu): chage body flex grow [YTFRONT-4221]

ytsaurus-ui-chart/.helmignore, ytsaurus-ui-chart/Chart.yaml, ytsaurus-ui-chart/templates/_helpers.tpl, ytsaurus-ui-chart/templates/config-map.yaml, ytsaurus-ui-chart/templates/deployment.yaml, ytsaurus-ui-chart/templates/ingress.yaml, ytsaurus-ui-chart/templates/service.yaml, ytsaurus-ui-chart/values.yaml
=> Create Helm chart for UI

packages/ui/src/ui/store/actions/system/masters.ts
This pull request suppose to fix issue https://github.com/ytsaurus/ytsaurus-ui/issues/529
I didn't manage to reproduce unavailable primary master, so for reproduce I just used invalid `primary_path`.
=> fix(System): now we are trying make a request to another primary masters if first one did not responded correctrly [#529]

packages/ui/src/ui/UIFactory.tsx, packages/ui/src/ui/pages/navigation/content/MapNode/MapNode.js
For now we have a fixed items which can be rendered in dropdown such as `Table`, `Link`, `Directory` and etc. 
With goal to add customization for dropdown items I added UIFactory method where we can change array as user want.
=> feat(Navigation/MapNode): add UIFactory.getMapNodeExtraCreateActions(...) method

packages/ui/src/ui/navigation/Navigation/PathEditorModal/CreateTableModal/CreateTableModal.tsx
https://nda.ya.ru/t/FHIeV0xX76naGK
=> feat(Query): changing the default name for new tables [YTFRONT-4249]

packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/store/reducer.tsx, packages/ui/src/ui/store/actions/navigation/tabs/tablet-errors.ts
https://nda.ya.ru/t/MnKO-jrM76nfCe
=> fix(Navigation): correct output of numbers in tablet errors [YTFRONT-4251]

packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/query_aco/reducer.ts, packages/ui/src/ui/pages/query-tracker/module/query_aco/selectors.ts
https://nda.ya.ru/t/CKdx2QDq76stEf
=> feat(Query): share query button [YTFRONT-4239]

packages/ui/src/ui/pages/query-tracker/QueriesList/QueriesHistoryList/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryACO/EditQueryACOModal/EditQueryACOModal.tsx, packages/ui/src/ui/pages/query-tracker/QueryACO/QueryACOSelect/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryACO/useQueryACO.ts, packages/ui/src/ui/pages/query-tracker/QueryMetaTable/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/query/utills.ts
https://nda.ya.ru/t/EwOLAQar76szxi
=> feat(Query): new query aco format [YTFRONT-4238]

packages/ui/src/ui/pages/query-tracker/QueryACO/EditQueryACOModal/EditQueryACOModal.tsx, packages/ui/src/ui/pages/query-tracker/QueryACO/QueryACOSelect/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/query_aco/selectors.ts
https://nda.ya.ru/t/EY_eoPzr77RuAd
=> feat(Query): multiple aco with backward compatible [YTFRONT-4238]

packages/ui/src/ui/pages/query-tracker/QueryResults/index.tsx
https://nda.ya.ru/t/snSyBw1F77cYJa
=> fix(Query): empty blocks in result [YTFRONT-4323]

packages/ui/src/ui/components/Dialog/controls/PoolSuggestControl/PoolSuggestControl.tsx, packages/ui/src/ui/pages/navigation/content/File/File.js, packages/ui/src/ui/pages/navigation/content/File/File.scss, packages/ui/src/ui/pages/navigation/content/MapNode/PathActions.tsx
https://nda.ya.ru/t/ExKmY0fQ77gFtU
=> hotfix for remote copy

packages/ui/src/ui/pages/query-tracker/QueryACO/EditQueryACOModal/EditQueryACOModal.tsx, packages/ui/src/ui/pages/query-tracker/QueryACO/QueryACOSelect/QueryACOSelect.scss, packages/ui/src/ui/pages/query-tracker/QueryACO/QueryACOSelect/hideSharedAco.ts, packages/ui/src/ui/pages/query-tracker/QueryACO/QueryACOSelect/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.scss, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ShareButton/index.scss, packages/ui/src/ui/pages/query-tracker/QueryResults/ShareButton/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/index.scss, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts
https://nda.ya.ru/t/JlQrnueF77PpgD
=> feat(Query): share button new design [YTFRONT-4286]

packages/ui/src/ui/pages/scheduling/Instruments/CreatePoolDialog/CreatePoolDialog.tsx
https://nda.ya.ru/t/ylBLKjur77jt6z
=> feat(Scheduling): changed validation for name [YTFRONT-4319]

packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.scss, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx
https://nda.ya.ru/t/JlQrnueF77PpgD
=> chore(Query): changed the distance between the buttons [YTFRONT-4286]

packages/ui/src/ui/components/MetaTable/templates/OperationTemplate.tsx, packages/ui/src/ui/components/OperationPool/OperationPool.scss, packages/ui/src/ui/components/OperationPool/OperationPool.tsx, packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/Runtime/Runtime.js, packages/ui/src/ui/pages/operations/OperationsList/OperationsListTable/OperationsListTable.js
https://nda.ya.ru/t/QaahS9D977iF3g
=> fix(Operations/Details/MetaTable): blinking UI when hover on long pool name [YTFRONT-4308]

packages/ui/src/ui/pages/query-tracker/Navigation/api/loadDynamicTable.ts, packages/ui/src/ui/pages/query-tracker/module/queryNavigation/actions.ts, packages/ui/src/ui/store/actions/navigation/content/table/readDynamicTable.ts, packages/ui/src/ui/store/actions/navigation/content/table/readStaticTable.ts, packages/ui/src/ui/store/actions/scheduling/scheduling-ts.ts, packages/ui/src/ui/store/actions/scheduling/scheduling.js
https://nda.ya.ru/t/U4ooiCFc77ijoC
=> fix(Navigation): error message in table [YTFRONT-4312]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/ui/components/MonacoEditor/MonacoEditor.tsx, packages/ui/src/ui/components/MonacoEditor/MonacoEditorThemes.tsx, packages/ui/src/ui/libs/monaco-yql-languages/_.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/createProvideSuggestionsFunction.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/generateSuggestions.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getDirectoryContent.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getPathFromMonacoModel.ts, packages/ui/src/ui/libs/monaco-yql-languages/s-expressions/s-expressions.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql_ansi/yql_ansi.ts
https://nda.ya.ru/t/Gz-ctXB_76vBxQ
=> feat(Query): path autocomplete [YTFRONT-4264]

packages/ui/src/server/ServerFactory.ts, packages/ui/src/server/components/vcs/GithubApi.ts, packages/ui/src/server/components/vcs/GitlabApi.ts, packages/ui/src/server/components/vcs/index.ts, packages/ui/src/server/controllers/vcs.ts, packages/ui/src/server/routes.ts, packages/ui/src/shared/constants/vcs.ts, packages/ui/src/shared/ui-settings.ts, packages/ui/src/shared/vcs.ts, packages/ui/src/ui/components/EditableAsText/EditableAsText.tsx, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/SettingsMenu/AddTokenForm.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/Vcs.scss, packages/ui/src/ui/pages/query-tracker/Vcs/Vcs.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsHeader/VcsHeader.scss, packages/ui/src/ui/pages/query-tracker/Vcs/VcsHeader/VcsHeader.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsItemsList/VcsItemsList.scss, packages/ui/src/ui/pages/query-tracker/Vcs/VcsItemsList/VcsItemsList.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsItemsList/VcsListFile.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsItemsList/VcsListPreview.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsPath/VcsPath.scss, packages/ui/src/ui/pages/query-tracker/Vcs/VcsPath/VcsPath.tsx, packages/ui/src/ui/pages/query-tracker/Vcs/VcsPath/index.ts, packages/ui/src/ui/pages/query-tracker/module/vcs/actions.ts, packages/ui/src/ui/pages/query-tracker/module/vcs/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/vcs/vcsSlice.ts
https://nda.ya.ru/t/oT2fclo_77Ykri
=> feat(Query): custom vcs [YTFRONT-4257]

packages/ui/src/shared/constants/yt-api-id.ts, packages/ui/src/ui/containers/Host/Host.tsx, packages/ui/src/ui/pages/system/Masters/ChangeMaintenanceButton.tsx, packages/ui/src/ui/pages/system/Masters/MasterGroup.js, packages/ui/src/ui/pages/system/Masters/MasterGroup.scss, packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/src/ui/pages/system/SchedulersAndAgents/Scheduler/Scheduler.tsx, packages/ui/src/ui/pages/system/SchedulersAndAgents/Schedulers.scss, packages/ui/src/ui/pages/system/SchedulersAndAgents/SchedulersAndAgents.js, packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/actions/system/schedulers.js, packages/ui/src/ui/store/selectors/system/masters.ts
https://nda.ya.ru/t/CXx7rIvE77xvcb
=> feat(System): maintenance button [YTFRONT-4217]

packages/ui/src/ui/pages/navigation/tabs/AccessLog/AccessLogFilters.tsx, packages/ui/src/ui/pages/navigation/tabs/AccessLog/AccessLogOpenQtButton.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/store/actions/navigation/tabs/access-log/access-log.ts
https://nda.ya.ru/t/K-lWnv1l78Ab27
=> feat(Navigation): open access logs in qt [YTFRONT-4345]

packages/ui/src/ui/libs/monaco-yql-languages/helpers/createProvideSuggestionsFunction.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getPathFromMonacoModel.ts, packages/ui/src/ui/libs/monaco-yql-languages/s-expressions/s-expressions.ts
https://nda.ya.ru/t/iyKYyhG278Kf4j
=> fix(Queries): chyt spyt path autocomplete [YTFRONT-4368]

packages/ui/src/ui/store/actions/navigation/modals/table-merge-sort-modal.tsx, packages/ui/src/ui/utils/utils.tsx
https://nda.ya.ru/t/VsjNs4XE78du97
=> fix(Sort,Merge): get rid of missing node errors [YTFRONT-4392]

packages/javascript-wrapper/package-lock.json, packages/javascript-wrapper/package.json
https://github.com/ytsaurus/ytsaurus-ui/issues/802
=> fix devDependencies https://github.com/ytsaurus/ytsaurus-ui/issues/802

packages/ui/src/ui/containers/ACL/RequestPermissions/RequestPermissions.tsx, packages/ui/src/ui/pages/navigation/Navigation/Navigation.js, packages/ui/src/ui/pages/navigation/Navigation/Navigation.scss
https://nda.ya.ru/t/r4_or_CV78wH8F
=> fix(Navigation): change request permission button [YTFRONT-4379]

packages/custom-ytsaurus-ui.example/src/server/configs/common.ts, packages/ui/src/server/configs/e2e/local.ts, packages/ui/src/shared/ui-settings.ts, packages/ui/src/ui/pages/system/Masters/MasterGroup.js, packages/ui/src/ui/pages/system/SchedulersAndAgents/Scheduler/Scheduler.tsx, packages/ui/src/ui/pages/system/helpers/makeShortSystemAddress.ts, packages/ui/tests/e2e/pages/system.spec.ts
https://nda.ya.ru/t/NzV8RS2z78oBSH
=> feat(System): new regexp shortname [YTFRONT-4386]

packages/ui/src/ui/pages/query-tracker/utils/query_generate.ts
https://nda.ya.ru/t/x-CmzFlO79AA6N
=> fix(Navigation): correct cluster name in yql query [YTFRONT-4274]

packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/Specification/Specification.js
https://nda.ya.ru/t/GlrYyVR179MtPG
=> fix(Operation/Details): Minified React error #31 [YTFRONT-4417]

packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorCloud.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorList.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.scss, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/ErrorTreeNode.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/ErrorTree/helpers/isInfoNode.ts
https://nda.ya.ru/t/uekzQpio797hDi
=> feat(Queries): info nodes in query error [YTFRONT-4342]

packages/ui/src/ui/components/CollapsibleSection/CollapsibleSection.tsx, packages/ui/src/ui/components/ElementsTable/ElementsTable.scss, packages/ui/src/ui/components/StickyContainer/StickyContainer.scss, packages/ui/src/ui/components/StickyContainer/StickyContainer.tsx, packages/ui/src/ui/pages/system/Chunks/Chunks.js, packages/ui/src/ui/pages/system/Chunks/Chunks.scss, packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/src/ui/pages/system/Masters/Masters.scss, packages/ui/src/ui/pages/system/Nodes/Nodes.tsx, packages/ui/src/ui/pages/system/ProxiesImpl/ProxiesImpl.tsx, packages/ui/src/ui/pages/system/SchedulersAndAgents/Schedulers.scss, packages/ui/src/ui/pages/system/SchedulersAndAgents/SchedulersAndAgents.js
https://nda.ya.ru/t/61tmZ7yF79Wcne
=> feat(System): headers of sections should be sticky [YTFRONT-4420]

packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx
https://nda.ya.ru/t/XtNnR1O-79bvfR
=> fix(Queries): run query hotkeys [YTFRONT-4462]

packages/ui/src/ui/store/actions/system/masters.ts
Reverts ytsaurus/ytsaurus-ui#864
=> Revert "chore(System): do not request data from endpoints with "maintenance" attribute"

packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/selectors/components/nodes/nodes/data.ts, packages/ui/src/ui/store/selectors/components/proxies/proxies.js, packages/ui/src/ui/store/selectors/components/versions/versions_v2.ts
=> fix(Components): use search of substring for 'Filter hosts'

packages/ui/src/ui/pages/query-tracker/module/engines.ts
https://nda.ya.ru/t/_Xe5DmC779pDVy
=> feat(Queries): change engine order [YTFRONT-4498]

packages/ui/src/ui/pages/scheduling/Scheduling/Scheduling.tsx
https://nda.ya.ru/t/jZipoeqO79uXRb
=> feat(Scheduling): hide all alerts [YTFRONT-4322]

packages/ui/src/server/utils/index.ts, packages/ui/src/shared/constants/settings-types.ts
https://nda.ya.ru/t/E9ckQdGU79z8q4
=> fix(Settigns): export DiscribedSettings type [YTFRONT-4499]

packages/ui/src/ui/pages/operations/OperationDetail/tabs/Jobs/OperationJobsTable/OperationJobsTable.js
https://nda.ya.ru/t/6XtKoHtb7A6vXi
=> fix(Operations): job tooltip value format [YTFRONT-4211]

packages/ui/src/ui/pages/navigation/content/MapNode/MapNodesTable.js
https://nda.ya.ru/t/O0qSNefr7A9g2x
=> fix(Navigation): keyboard navigation [YTFRONT-4493]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/tests/screenshots/pages/navigation/navigation.table.base.screen.ts
https://nda.ya.ru/t/pLvvBq2f7ABNr3
=> chore(UI) ui rc-slider version [YTFRONT-4513]

packages/ui/src/ui/store/actions/settings/index.ts
https://nda.ya.ru/t/4PaM2pPh7AGMLS
=> fix(UI): celebration theme fix

packages/ui/src/ui/styles/redefinitions/common/common.scss
https://nda.ya.ru/t/o6_1YUDH7AKLxz
=> fix(Toaster): line break in toaster content [YTFRONT-4543]

packages/ui/src/ui/components/ColumnCell/ColumnCell.tsx, packages/ui/src/ui/containers/CellPreviewModal/CellPreviewModal.tsx, packages/ui/src/ui/pages/navigation/content/Table/DataTableWrapper/DataTableWrapper.js, packages/ui/src/ui/pages/query-tracker/QueryResultsView/YQLTable/YQLTable.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/cell-preview/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query_result/utils/format.ts, packages/ui/src/ui/store/actions/navigation/modals/cell-preview/dynamic-table.ts, packages/ui/src/ui/store/actions/navigation/modals/cell-preview/format.ts, packages/ui/src/ui/store/actions/navigation/modals/cell-preview/index.ts, packages/ui/src/ui/store/actions/navigation/modals/cell-preview/static-table.ts, packages/ui/src/ui/store/reducers/modals/cell-preview.ts, packages/ui/src/ui/utils/navigation/prepareColumns.tsx, packages/ui/src/ui/utils/yql-types.ts
https://nda.ya.ru/t/bj_N978J7AKJpw
=> feat(CellPreview): add incomplete images cell preview [#773]

packages/ui/src/server/components/vcs/GitlabApi.ts, packages/ui/src/server/controllers/vcs.ts
https://nda.ya.ru/t/aXs6pypZ7AKe4W
=> feat(VCS): new list sort order [YTFRONT-4520]

packages/ui/src/ui/store/reducers/accounts/accounts/url-mapping.ts
https://nda.ya.ru/t/n16LFp3w7ASM8J
=> fix(Accounts): medium filter value in url [YTFRONT-4567]

packages/ui/src/ui/pages/navigation/Navigation/PathEditorModal/CopyObjectModal/CopyObjectModal.js, packages/ui/src/ui/store/actions/navigation/modals/copy-object.tsx
https://nda.ya.ru/t/Xyfw1dOD7AWzj2
=> feat(CopyObjectModal): add recursive folders creating while copying [YTFRONT-3041]

packages/ui/src/ui/pages/navigation/Navigation/PathEditorModal/CopyObjectModal/CopyObjectModal.js
https://nda.ya.ru/t/-wnxDf2N7BAqbb
=> fix(CopyObjectModal): change checkbox text [YTFRONT-3041]

packages/ui/src/ui/pages/operations/OperationDetail/tabs/Jobs/OperationJobsTable/OperationJobsTable.js
https://nda.ya.ru/t/XFRfrulc7BJJKz
=> chore: made job abortion and abandonding warnings more precise

packages/ui/src/ui/store/reducers/operations/jobs/jobs.js, packages/ui/src/ui/store/reducers/operations/jobs/url-mapping.ts
[Issue 775](https://github.com/ytsaurus/ytsaurus-ui/issues/775).
=> fix(Jobs): fixed filter by job state, now it's correctly applying from URL [#775]

packages/ui/src/ui/pages/navigation/content/MapNode/MultipleActions.tsx
https://nda.ya.ru/t/AeXkDXC47BAp8G
=> fix(MultipleActions): filter empty sections [YTFRONT-4627]

packages/ui/src/ui/store/actions/scheduling/scheduling-ts.ts
https://nda.ya.ru/t/diDpUZLh7BUCqU
=> fix(Scheduling): replace deprecated attribute [YTFRONT-4652]

packages/ui/src/ui/store/actions/system/masters.ts, packages/ui/src/ui/store/reducers/system/masters.ts
Related issue: https://github.com/ytsaurus/ytsaurus-ui/issues/959
=> revert(System): return requests to maintenance hosts [#959]

packages/ui/src/ui/pages/navigation/content/Table/UploadManager/UploadManagerCreate.tsx, packages/ui/src/ui/store/selectors/navigation/content/map-node.js
https://nda.ya.ru/t/bYoXX6Dr7BUSZJ
=> fix(Navigation): check file existence by name [YTFRONT-4638]

packages/ui/src/shared/constants/settings-types.ts, packages/ui/src/shared/constants/settings.ts, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/pages/query-tracker/Plan/GraphEditor/PopupLayer/HoverPopup.tsx, packages/ui/src/ui/store/selectors/settings/settings-ts.ts
https://nda.ya.ru/t/_8tGJoCn7Bk7k3
=> fix(Queries): graph nodes clickable again [YTFRONT-4682]

packages/ui/src/shared/constants/settings-types.ts, packages/ui/src/ui/UIFactory/default-ui-factory.tsx, packages/ui/src/ui/UIFactory/index.tsx, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/libs/monaco-yql-languages/_.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.contribution.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.contribution.ts, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditor.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/querySuggestionsModule/createInlineSuggestions.ts, packages/ui/src/ui/pages/query-tracker/querySuggestionsModule/useMonacoQuerySuggestions.ts, packages/ui/src/ui/store/selectors/settings/settings-queries.ts
https://nda.ya.ru/t/NDr8AtXF7BYR9e
=> feat(Queries): inline suggestions [YTFRONT-4612]

packages/ui/src/ui/pages/navigation/Navigation/ContentViewer/helpers/getComponentByContentType.ts
https://nda.ya.ru/t/AXi2VCUY7BmRso
=> feat(Navigation/ContentViewer): add ability to view chaos_cells [YTFRONT-3653]

packages/ui/src/ui/pages/navigation/content/Table/UploadManager/UploadManagerCreate.tsx
https://nda.ya.ru/t/5iQLOJXu7BuwS8
=> fix(Navigation): xlsx types checkbox off by default [YTFRONT-4699]

packages/ui/src/ui/constants/chyt-page.ts, packages/ui/src/ui/pages/chyt/ChytPageClique/ChytPageCliqueTabs.tsx
https://nda.ya.ru/t/3qZfMWcM7Buv45
=> feat(CHYT/Tabs): add tab for logs link [YTFRONT-4675]

packages/ui/src/ui/UIFactory/index.tsx, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/pages/query-tracker/querySuggestionsModule/useMonacoQuerySuggestions.ts
https://nda.ya.ru/t/zmaRntUR7Bxp7c
=> feat(Settings): change suggestions settings item [YTFRONT-4703]

packages/ui/src/ui/pages/navigation/Navigation/NavigationError/NavigationError.tsx, packages/ui/src/ui/pages/navigation/Navigation/NavigationError/RequestPermission/RequestPermission.tsx, packages/ui/src/ui/store/actions/navigation/index.js
https://nda.ya.ru/t/8qWpX0rL7ByJV9
=> fix(Navigation): add missing attribute & fix copy button

packages/ui/src/ui/pages/navigation/content/Table/TableOverview/TableOverview.js
https://nda.ya.ru/t/DFMc5yHX7ByNQY
=> fix(Navigation/Table): query buttons should be always visible [YTFRONT-4706]

packages/ui/src/ui/components/MetaTable/templates/OperationTemplate.tsx, packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/Specification/Specification.js, packages/ui/src/ui/utils/operations/tabs/details/specification/specification.ts
https://nda.ya.ru/t/OMoblepI7Buw4E
=> feat(Operations/Details): display layer paths [YTFRONT-4618]

packages/ui/src/ui/pages/query-tracker/QueryResultsView/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/system/Masters/Masters.js, packages/ui/tests/e2e/pages/system.spec.ts
https://nda.ya.ru/t/uemnrKt77ByG2Q
=> feat(Queries): add full result link [YTFRONT-4674]

packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx
https://nda.ya.ru/t/5QMwkj757C7kPq
=> chore(Settings): add setting item id [YTFRONT-4731]

packages/ui/src/ui/store/actions/operations/detail.ts
https://nda.ya.ru/t/awCwZ66s7CKu8c
=> fix(Operations): utf8 statistic [YTFRONT-4700]

packages/ui/src/ui/store/actions/components/nodes/nodes.ts
https://nda.ya.ru/t/4Cz_cFqs7CUjLZ
=> fix(Components): processing node list data [YTFRONT-4765]

packages/ui/src/ui/libs/monaco-yql-languages/helpers/getDirectoryContent.ts
https://nda.ya.ru/t/AzgaB6_z7CUpuk
https://github.com/ytsaurus/ytsaurus-ui/issues/1027
Fix demonstration:
https://github.com/user-attachments/assets/4c340a69-5c71-40f6-87e5-b89351eb6fa8
=> fix: fixed insert of suggested path in query editor [#1027]

.github/workflows/ci-e2e.yaml, packages/ui/tests/playwright.config.ts
https://nda.ya.ru/t/d3Vipsrz7BsJtu
=> chore: change playwright reporter [YTFRONT-4663]

packages/ui/src/ui/pages/components/tabs/nodes/Nodes/Nodes.scss
https://nda.ya.ru/t/6Ip9gu6G7CiBSW
=> fix(Nodes): wrong color in contrast high theme [YTFRONT-4610]

packages/ui/src/ui/pages/query-tracker/Navigation/ClusterList/ClusterList.scss, packages/ui/src/ui/pages/query-tracker/Navigation/ClusterList/ClusterList.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/ItemsList.scss, packages/ui/src/ui/pages/query-tracker/Navigation/ItemsList.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/NavigationTable/SchemaTab.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/NodeList/NodeList.scss, packages/ui/src/ui/pages/query-tracker/Navigation/NodeList/NodeList.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/NodeList/NodeListRow.scss, packages/ui/src/ui/pages/query-tracker/Navigation/NodeList/NodeListRow.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/api/loadTableAttributes.ts, packages/ui/src/ui/pages/query-tracker/Navigation/helpers/createTableSelect.ts, packages/ui/src/ui/pages/query-tracker/Navigation/helpers/getIconBySortType.ts, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryClusterSelector/QueryClusterItem.scss, packages/ui/src/ui/pages/query-tracker/module/queryNavigation/actions.ts, packages/ui/src/ui/pages/query-tracker/module/queryNavigation/queryNavigationSlice.ts, packages/ui/src/ui/pages/query-tracker/module/queryNavigation/selectors.ts
https://nda.ya.ru/t/5U8G-PR67CjoFg
=> fix(Queries): improve navigation speed [YTFRONT-4771]

packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.tsx, packages/ui/src/ui/store/reducers/global/supported-features.ts, packages/ui/src/ui/store/reducers/tablet_cell_bundles/index.ts, packages/ui/src/ui/store/selectors/global/supported-features.ts, packages/ui/src/ui/utils/tablet_cell_bundles/bundles/bundle-editor-dialog/index.ts
https://nda.ya.ru/t/TRWRh_417CiH2o
=> feat(Bundles): add query memory limit [YTFRONT-4651]

packages/ui/src/ui/pages/components/GroupSuggest/GroupSuggest.tsx, packages/ui/src/ui/pages/users/UsersPageFilters/UsersPageFilters.js
https://nda.ya.ru/t/tKSdtWaU7CgeH3
=> fix(Users/GroupSuggest): group suggest visibility [YTFRONT-4737]

packages/ui/src/ui/pages/navigation/content/Table/DownloadManager/DownloadManager.tsx, packages/ui/src/ui/store/actions/navigation/content/table/download-manager.tsx
https://nda.ya.ru/t/PUm7fUxF7Cji3M
=> fix(Navigation/DownloadManager): provide more details in error toaster [YTFRONT-4790]

packages/ui/src/ui/pages/navigation/content/Table/TableOverview/TableOverview.js, packages/ui/src/ui/store/actions/navigation/content/table/table.js, packages/ui/src/ui/store/selectors/navigation/content/table-ts.ts
https://nda.ya.ru/t/A3WxNWUE7CtT5V
=> fix(Navigation/Table): fix offset and pagination of unmounted tables [YTFRONT-4021]

packages/ui/src/ui/UIFactory/index.tsx, packages/ui/src/ui/containers/AppNavigation/TopRowContent/TopRowContent.tsx, packages/ui/src/ui/containers/ClusterPage/ClusterPage.js, packages/ui/src/ui/pages/chyt/ChytCliqueActions/ChytCliqueActions.tsx, packages/ui/src/ui/store/selectors/global/experimental-pages.ts
https://nda.ya.ru/t/HDRmFjC17AeZVW
=> chore(Queries): remove isQueryTrackerAllowed selector [YTFRONT-4463]

packages/ui/src/ui/pages/query-tracker/Plan/GraphEditor/canvas/NodeBlock.tsx, packages/ui/src/ui/pages/query-tracker/Plan/GraphEditor/constants/index.ts
https://nda.ya.ru/t/CdY8SIoo7D2g3G
=> feat(Queries/Graph): increased visibility of the number of tasks [YTFRONT-4812]

packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryCliqueSelector/QueryCliqueItem.scss, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryCliqueSelector/QueryCliqueItem.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QueryCliqueSelector/QueryCliqueSelector.tsx, packages/ui/src/ui/pages/query-tracker/QueryTrackerTopRow/QuerySelectorsByEngine.tsx, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts
https://nda.ya.ru/t/0x1BfK0w7D7QRP
=> feat(Queries): show status in chyt clique selector [YTFRONT-4825]

packages/ui/src/ui/libs/monaco-yql-languages/helpers/getDirectoryContent.ts
https://nda.ya.ru/t/UXFVC2wL7D5Y5R
=> fix(Queries/Monaco): cut path suggest [YTFRONT-4806]

packages/ui/src/ui/libs/monaco-yql-languages/helpers/createProvideSuggestionsFunction.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getTemplateSuggestions.ts, packages/ui/tests/e2e/pages/query-tracker.spec.ts
https://github.com/ytsaurus/ytsaurus-ui/issues/1032
=> fix(Queries): fixed query suggest, now `` are fully replaced by `//` [#1032]

packages/ui/src/ui/pages/query-tracker/QueryStatus/index.scss, packages/ui/src/ui/pages/query-tracker/QueryStatus/index.tsx
https://nda.ya.ru/t/3piCxUOe7D8uMT
=> fix(Queries/History): status icon [YTFRONT-4821]

packages/ui/src/ui/pages/system/SchedulersAndAgents/Scheduler/Scheduler.tsx, packages/ui/src/ui/pages/system/SchedulersAndAgents/Schedulers.scss
https://nda.ya.ru/t/Iv-IkmVJ7DH3Kw
=> fix(System): masters on small monitors [YTFRONT-4830]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/shared/constants/settings-types.ts, packages/ui/src/ui/components/MonacoEditor/MonacoEditor.scss, packages/ui/src/ui/components/MonacoEditor/MonacoEditor.tsx, packages/ui/src/ui/containers/SettingsPanel/settings-description.tsx, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditorMonaco.scss, packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditorMonaco.tsx, packages/ui/src/ui/store/selectors/settings/settings-ts.ts
https://nda.ya.ru/t/k0tE2PB47DDhmJ
=> feat(Monaco): vim mode[YTFRONT-4807]

packages/ui/src/ui/components/RedirectConfirmModal/RedirectConfirmModal.tsx, packages/ui/src/ui/components/RedirectConfirmModal/index.ts, packages/ui/src/ui/pages/query-tracker/QueryTracker/QueryTracker.tsx, packages/ui/src/ui/pages/query-tracker/module/query-tracker-contants.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts, packages/ui/src/ui/pages/query-tracker/module/query/reducer.ts
https://nda.ya.ru/t/i35qUnrL7D4JkD
=> feat(Queries): redirect confirm modal [YTFRONT-4809]

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getDirectoryContent.ts
https://nda.ya.ru/t/8RP_t7fG7DRD8Q
=> feat: update @ytsaurus/javascript-wrapper

packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryProgress.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/helpers/calculateQueryProgress.ts, packages/ui/src/ui/pages/query-tracker/module/api.ts
https://nda.ya.ru/t/3v3bTFvq7DDrCJ
=> feat(Queries): chyt progress [YTFRONT-4833]

packages/ui/src/ui/components/ColumnSelector/ColumnSelector.js, packages/ui/src/ui/components/ColumnSelector/ColumnSelector.scss, packages/ui/src/ui/utils/navigation/content/table/columns.js
https://nda.ya.ru/t/ik21qiC_7DJsjE
=> fix(Navigation): do not hide key columns in dyn tables [YTFRONT-4826]

packages/ui/src/ui/pages/operations/OperationDetail/tabs/Jobs/OperationJobsTable/JobDetails.tsx
https://nda.ya.ru/t/fxBEPT-o7DUANd
=> fix(Operations): big rows count in jobs [YTFRONT-4854]

packages/ui/src/ui/pages/navigation/modals/TableMergeSortModal/TableSortByControl.tsx
https://nda.ya.ru/t/hGp8EjTv7Dftgv
=> fix(TableSortModal): column encoding [YTFRONT-4873]

packages/ui/scripts/dev.localmode-env.sh, packages/ui/src/server/ServerFactory.ts, packages/ui/src/server/components/utils.ts, packages/ui/src/server/config.localcluster.ts, packages/ui/src/server/constants/index.ts, packages/ui/src/shared/constants/index.ts, packages/ui/src/shared/lib.ts, packages/ui/src/shared/utils/index.ts, packages/ui/src/ui/pages/query-tracker/module/query/actions.ts
https://nda.ya.ru/t/yeXI1meM7Dg5pg
=> fix(localmode): sync cluster_name [YTFRONT-4326]

packages/ui/src/ui/pages/navigation/tabs/Queue/views/Exports/ExportsEdit/ExportsEdit.tsx, packages/ui/src/ui/pages/navigation/tabs/Queue/views/Exports/ExportsEditDialog/ExportsEditDialog.tsx, packages/ui/src/ui/store/api/navigation/tabs/queue/queue.ts, packages/ui/src/ui/store/api/yt/endpoints/executeBatch.ts, packages/ui/src/ui/store/api/yt/index.ts
https://nda.ya.ru/t/zuCvubzr7Dpd7s
=> fix: batch api types

packages/ui/src/ui/pages/navigation/content/Table/DownloadManager/ConfirmButton.tsx, packages/ui/src/ui/pages/navigation/content/Table/DownloadManager/DownloadManager.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryResultDownloadManager.tsx, packages/ui/src/ui/store/actions/navigation/content/table/download-manager.tsx, packages/ui/src/ui/utils/copy-file-to-clipboard.ts
https://nda.ya.ru/t/siTLC5Tq7DuEpX
=> feat(Download): copy to clipboard [YTFRONT-4895]

packages/ui/src/ui/store/actions/accounts/account-usage-diff.ts, packages/ui/src/ui/store/actions/accounts/account-usage.ts
https://nda.ya.ru/t/x_h00qf27ERq3r
=> fix(Account): normalize timestamp [YTFRONT-4913]

packages/ui/src/ui/store/actions/navigation/content/replicated-table.js
https://nda.ya.ru/t/cHQ45UEk7EV7qe
=> fix(ChaosReplicatedTable): use `alter_table_replica` [YTFRONT-4796]

packages/ui/src/ui/store/actions/acl.ts, packages/ui/src/ui/store/reducers/acl/acl.ts, packages/ui/src/ui/utils/acl/acl-types.ts
https://nda.ya.ru/t/F61olFgz7EcDqD
=> fix(ACL): bring back `inheritAcl` field [YTFRONT-4718]

packages/ui/src/ui/UIFactory/default-ui-factory.tsx
Issue: https://github.com/ytsaurus/ytsaurus-ui/issues/1120
=> fix: changed default value of UIFactory.onChytAliasSqlClick - now sql button is working on chyt page

packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/appearance.ts
https://nda.ya.ru/t/laeHLZl37Ef2Ci
=> chore: remove field 'ClusterConfig.isLocalCluster' [TFRONT-4936]

.github/workflows/ci-e2e.yaml, .github/workflows/ci-statoscope.yaml, packages/ui/build.app.config.ts, packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/ui/common/utils/url.js, packages/ui/src/ui/common/utils/url.ts, packages/ui/src/ui/components/Suggest/Suggest.scss, packages/ui/src/ui/components/Yson/StructuredYsonVirtualized/StructuredYsonVirtualized.scss, packages/ui/src/ui/components/action/action.js, packages/ui/src/ui/containers/ManageTokens/ManageTokensModalContent/ManageTokensModalContent.scss, packages/ui/src/ui/containers/PathEditor/PathEditor.scss, packages/ui/src/ui/legacy-styles/elements/suggest/suggest.scss, packages/ui/src/ui/pages/odin/controls/OdinOverview.tsx, packages/ui/src/ui/pages/tablet_cell_bundles/bundles/BundleEditorDialog/BundleEditorDialog.scss, packages/ui/src/ui/store/selectors/acl.ts, packages/ui/src/ui/utils/acl/index.ts, packages/ui/statoscope.config.js, packages/ui/tsconfig.json
https://nda.ya.ru/t/Mh7vrPO37EKu9T
=> chore: rspack migration

packages/ui/src/ui/pages/query-tracker/QueryEditor/QueryEditorMonaco.tsx
https://nda.ya.ru/t/QORpK1Yw7EidCd
=> feat(Queries/Monaco): scroll editor to selected line [YTFRONT-4915]

packages/ui/src/ui/styles/redefinitions/common/common.scss
https://nda.ya.ru/t/ZQd1vsD97EqbkD
=> fix: color reassign

packages/ui/README.md, packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/pages/accounts/Accounts/Accounts.tsx, packages/ui/src/ui/store/actions/accounts/account-usage-diff.ts, packages/ui/src/ui/store/actions/accounts/account-usage.ts, packages/ui/src/ui/store/selectors/global/index.ts
https://nda.ya.ru/t/jeG0_uH67EsJtP
=> feat(Accounts): add custom accounts usage base url [YTFRONT-4927]

packages/ui/src/ui/pages/query-tracker/Navigation/NavigationHeader/HeaderActions.tsx, packages/ui/src/ui/pages/query-tracker/Navigation/NavigationHeader/NavigationHeader.scss, packages/ui/src/ui/pages/query-tracker/Navigation/NavigationHeader/NavigationHeader.tsx
https://nda.ya.ru/t/bZN0tWpI7FGsLa
=> feat(Queries/Navigation): add open new tab button [YTFRONT-4985]

packages/ui/src/ui/UIFactory/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryChartTab.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/QueryResultActions/QueryProgress.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/helpers/calculateQueryProgress.ts, packages/ui/src/ui/pages/query-tracker/QueryResults/hooks/useQueryResultTabs.tsx, packages/ui/src/ui/pages/query-tracker/QueryResults/index.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/Chart.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/ChartLeftMenu.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/QueryResultsVisualization.scss, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/QueryResultsVisualization.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/QueryResultsVisualizationWrap.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/components/Wizard/Wizard.tsx, packages/ui/src/ui/pages/query-tracker/QueryResultsVisualization/index.tsx, packages/ui/src/ui/pages/query-tracker/module/api.ts, packages/ui/src/ui/pages/query-tracker/module/query/selectors.ts, packages/ui/src/ui/pages/query-tracker/module/query/utills.ts, packages/ui/src/ui/pages/query-tracker/module/queryChart/actions.ts, packages/ui/src/ui/pages/query-tracker/module/queryChart/queryChartSlice.ts, packages/ui/src/ui/pages/query-tracker/module/queryChart/selectors.ts
https://nda.ya.ru/t/8pZwBAyX7FAK9D
=> feat(Queries): add multi progress [YTFRONT-4999]

packages/ui/src/ui/pages/navigation/NavigationDescription/hooks/use-description-type-on-load.ts, packages/ui/src/ui/pages/navigation/NavigationDescription/hooks/use-description.ts
https://nda.ya.ru/t/YBozYRez7FLaHb
=> feat(Navigation/Description): display loaded description [YTFRONT-5015]

packages/ui/src/ui/components/Dialog/controls/AccountsMultiple/AccountsMultiple.tsx
https://nda.ya.ru/t/QyGgGsCE7FLt2u
=> feat(Dialog/AccountsMultiple): add items deleting labels [YTFRONT-3400]

packages/ui/src/shared/yt-types.d.ts, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Operations/OperationsWidgetContent/use-operations-widget.ts, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Operations/OperationsWidgetControls/OperationsWidgetControls.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Operations/settings/index.tsx, packages/ui/src/ui/store/api/dashboard2/operations/operations.ts, packages/ui/src/ui/store/selectors/dashboard2/operations.ts
https://nda.ya.ru/t/8Bzk82eG7FTEnX
=> feat(Dashboard2/Operations): add pool setting [YTFRONT-3400]

packages/ui/src/ui/store/actions/operations/jobs.ts, packages/ui/src/ui/store/reducers/operations/jobs/jobs.ts, packages/ui/src/ui/store/reducers/operations/jobs/url-mapping.ts, packages/ui/src/ui/store/selectors/operations/index.ts
https://nda.ya.ru/t/KRMqehvA7FUjoP
=> feat(Operation/Jobs): add 'With interruption info' [YTFRONT-4810]

packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/DetailedJobsCounter/DetailedJobsCounter.js, packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/DetailedJobsCounter/JobCounters.scss, packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/DetailedJobsCounter/JobCounters.tsx
https://nda.ya.ru/t/n-rgKNSp7FU8KS
=> fix(Operation/Details/Tasks/Aborted statistics): add 'Hide empty' filter  [YTFRONT-5012]

packages/ui/src/ui/store/selectors/accounts/accounts.js
https://nda.ya.ru/t/lG9WbwDo7FZibj
=> fix(Accounts): fix or 'Aggregation' [YTFRONT-5024]

packages/ui/src/ui/components/Dialog/controls/AccountsMultiple/AccountsMultiple.tsx, packages/ui/src/ui/components/common/ColumnSelector/ColumnSelector.scss, packages/ui/src/ui/constants/dashboard2/index.ts, packages/ui/src/ui/pages/dashboard2/Dashboard/Dashboard.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Accounts/AccountsWidgetContent/AccountsWidgetContent.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Accounts/AccountsWidgetContent/cells/AccountsProgressCell.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Accounts/AccountsWidgetControls/AccountsWidgetControls.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Accounts/settings/index.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/Widgets/Services/ServicesWidgetContent/ServicesWidgetContent.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/components/WidgetSettings/WidgetSettings.tsx, packages/ui/src/ui/pages/dashboard2/Dashboard/utils/registerPlugins.tsx, packages/ui/src/ui/store/actions/dashboard2/accounts.ts, packages/ui/src/ui/store/actions/dashboard2/dashboard.ts, packages/ui/src/ui/store/actions/dashboard2/utils.ts, packages/ui/src/ui/store/api/accounts/index.ts, packages/ui/src/ui/store/api/accounts/usable.ts, packages/ui/src/ui/store/api/dashboard2/accounts/accounts.ts, packages/ui/src/ui/store/api/dashboard2/operations/operations.ts, packages/ui/src/ui/store/selectors/dashboard2/accounts.ts, packages/ui/src/ui/store/selectors/dashboard2/dashboard.ts, packages/ui/src/ui/utils/dashboard2/make-default-config.ts
https://nda.ya.ru/t/IjEspjvX7FYVde
=> feat(Dashboard2/Accounts): columns for mediums [YTFRONT-3400]

packages/ui/src/ui/pages/navigation/tabs/AccessLog/AccessLogFilters.tsx, packages/ui/src/ui/store/selectors/navigation/tabs/access-log.ts
https://nda.ya.ru/t/6tE4IDvU7FasPn
=> fix(Navigation/AccessLog): add 'Recursive' checkbox filter [YTFRONT-5023]

packages/ui/src/ui/pages/navigation/tabs/Tablets/Tablets.js
https://nda.ya.ru/t/5WYq8zZd7FitzM
=> fix(Navigation/Tablets): arrow click [YTFRONT-5030]

packages/ui/src/ui/components/MonacoEditor/MonacoEditor.tsx, packages/ui/src/ui/components/MonacoEditor/MonacoEditorThemes.tsx, packages/ui/src/ui/libs/monaco-yql-languages/clickhouse/clickhouse.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getClusterAndPath.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getColumnSuggestions.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getDirectoryContent.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/getPathFromMonacoModel.ts, packages/ui/src/ui/libs/monaco-yql-languages/helpers/loadTableData.ts, packages/ui/src/ui/libs/monaco-yql-languages/s-expressions/s-expressions.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql/yql.ts, packages/ui/src/ui/libs/monaco-yql-languages/yql_ansi/yql_ansi.ts, packages/ui/src/ui/pages/query-tracker/QueryEditor/decorators/LinkDecorator.ts
https://nda.ya.ru/t/9BiVmINN7FvKq3
=> fix(Queries): multiple paths in one line [YTFRONT-4920]

packages/ui/src/ui/UIFactory/index.tsx, packages/ui/src/ui/components/Block/Block.scss, packages/ui/src/ui/components/Block/Block.tsx, packages/ui/src/ui/components/ErrorDetails/ErrorDetails.scss, packages/ui/src/ui/components/StatusLabel/StatusLabel.tsx, packages/ui/src/ui/constants/operations/detail.ts, packages/ui/src/ui/pages/operations/OperationDetail/OperationDetail.tsx
https://nda.ya.ru/t/wk40Pg9o7Fb2Zy
=> feat(Operations/PyDLTelemetry): add uifactory property for tab [YTFRONT-4892]
